package com.leetcode.daliy;

import java.util.Stack;

/**
 * @author TSN
 * @date 2019/1/7
 * @Description
 */
public class L389_FindTheDifference {
    /**
     * Given two strings s and t which consist of only lowercase letters.
     *
     * String t is generated by random shuffling string s and then add one more letter at a random position.
     *
     * Find the letter that was added in t.
     *
     * Example:
     *
     * Input:
     * s = "abcd"
     * t = "abcde"
     *
     * Output:
     * e
     *
     * Explanation:
     * 'e' is the letter that was added.
     */
    public static void main(String[] args) {
        System.out.println(findTheDifference("abcd","abcde"));
    }


    public static char findTheDifference(String s, String t) {
        char result = 0;
        // ^  与或 相同为0   描述是只有一个不同 所以 可以用他  相同的都消掉了  只剩下不同的
        for (int i = 0; i < t.length(); i++) {
            result ^= t.charAt(i);
        }
        for (int i = 0; i < s.length(); i++) {
            result ^= s.charAt(i);
        }
        return result;
    }

}
